package tables;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 15-dic-2016 9:17:13 by Hibernate Tools 5.2.0.CR1

/**
 * Plane generated by hbm2java
 */
@Entity
@Table(name="Plane")
public class Plane implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name="plane_id")
	private long planeId;
	
	@Column(name="terminal")
	private int terminal;
	
	@Column(name="mode_status")
	private String modeStatus;

	public Plane() {
	}

	public Plane(long planeId, int terminal, String modeStatus) {
		this.planeId = planeId;
		this.terminal = terminal;
		this.modeStatus = modeStatus;
	}

	public long getPlaneId() {
		return this.planeId;
	}

	public void setPlaneId(long planeId) {
		this.planeId = planeId;
	}

	public int getTerminal() {
		return this.terminal;
	}

	public void setTerminal(int terminal) {
		this.terminal = terminal;
	}

	public String getModeStatus() {
		return this.modeStatus;
	}

	public void setModeStatus(String modeStatus) {
		this.modeStatus = modeStatus;
	}
}
