/*
 * 
 */
package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * PlaneMovements generated by hbm2java.
 */

@Entity
@Table(name="PlaneMovements")
public class PlaneMovements implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;
	
	/** The Constant OUT. */
	private static final int IN = 0, OUT = 1;

	/** The id. */
	@Id
	@Column(name="id")
	private int id;
	
	/** The plane id. */
	@Column(name="plane_id")
	private int plane_id;
	
	/** The posx. */
	@Column(name="posx")
	private Double posx;
	
	/** The posy. */
	@Column(name="posy")
	private Double posy;
	
	/** The out. */
	@Column(name="out")
	private int out;

	/**
	 * Instantiates a new plane movements.
	 */
	public PlaneMovements() {
	}

	/**
	 * Instantiates a new plane movements.
	 *
	 * @param id the id
	 * @param plane_id the plane id
	 */
	public PlaneMovements(int id, int plane_id) {
		this.id = id;
		this.plane_id = plane_id;
		this.out = IN;
	}

	/**
	 * Instantiates a new plane movements.
	 *
	 * @param id the id
	 * @param plane_id the plane id
	 * @param posx the posx
	 * @param posy the posy
	 */
	public PlaneMovements(int id, int plane_id, Double posx, Double posy) {
		this.id = id;
		this.plane_id = plane_id;
		this.posx = posx;
		this.posy = posy;
		this.out = IN;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the planes.
	 *
	 * @return the planes
	 */
	public int getPlanes() {
		return this.plane_id;
	}

	/**
	 * Sets the planes.
	 *
	 * @param plane_id the new planes
	 */
	public void setPlanes(int plane_id) {
		this.plane_id = plane_id;
	}

	/**
	 * Gets the posx.
	 *
	 * @return the posx
	 */
	public Double getPosx() {
		return this.posx;
	}

	/**
	 * Sets the posx.
	 *
	 * @param posx the new posx
	 */
	public void setPosx(Double posx) {
		this.posx = posx;
	}

	/**
	 * Gets the posy.
	 *
	 * @return the posy
	 */
	public Double getPosy() {
		return this.posy;
	}

	/**
	 * Sets the posy.
	 *
	 * @param posy the new posy
	 */
	public void setPosy(Double posy) {
		this.posy = posy;
	}
	
	/**
	 * Checks if is out.
	 *
	 * @return true, if is out
	 */
	public boolean isOut() {
		return (this.out == OUT);
	}
	
	/**
	 * Sets the out.
	 */
	public void setOut() {
		this.out = OUT;
	}

	/**
	 * Gets the out.
	 *
	 * @return the out
	 */
	public int getOut() {
		return out;
	}

	/**
	 * Sets the out.
	 *
	 * @param out the new out
	 */
	public void setOut(int out) {
		this.out = out;
	}
	
}
