/*
 * 
 */
package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * PlaneMovements generated by hbm2java.
 */

@Entity
@Table(name="PlaneMovements")
public class PlaneMovements implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;
	
	/** The Constant IN for when the plane is on the airport. */
	private static final int IN = 0, 
	/** The Constant OUT for when the plane leaves the airport. */
			OUT = 1;

	/** The movement id. */
	@Id
	@Column(name="id")
	private int id;
	
	/** The plane id. */
	@Column(name="plane_id")
	private int plane_id;
	
	/** The X coordinate. */
	@Column(name="posx")
	private Double posx;
	
	/** The Y coordinate. */
	@Column(name="posy")
	private Double posy;
	
	/** Indicates when a plane leaves the airport. */
	@Column(name="out")
	private int out;

	/**
	 * Instantiates a new plane movements.
	 */
	public PlaneMovements() {
	}

	/**
	 * Instantiates a new plane movement with a certain id and plane.
	 *
	 * @param id the id
	 * @param plane_id the plane id
	 */
	public PlaneMovements(int id, int plane_id) {
		this.id = id;
		this.plane_id = plane_id;
		this.out = IN;
	}

	/**
	 * Instantiates a new plane movement with a certain id, plane and position coordinates
	 *
	 * @param id the id
	 * @param plane_id the plane id
	 * @param posx the X coordinate
	 * @param posy the Y coordinate
	 */
	public PlaneMovements(int id, int plane_id, Double posx, Double posy) {
		this.id = id;
		this.plane_id = plane_id;
		this.posx = posx;
		this.posy = posy;
		this.out = IN;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the plane id.
	 *
	 * @return the plane id
	 */
	public int getPlanes() {
		return this.plane_id;
	}

	/**
	 * Sets the plane id.
	 *
	 * @param plane_id the new plane id
	 */
	public void setPlanes(int plane_id) {
		this.plane_id = plane_id;
	}

	/**
	 * Gets the X coordinate.
	 *
	 * @return the X coordinate
	 */
	public Double getPosx() {
		return this.posx;
	}

	/**
	 * Sets the X coordinate.
	 *
	 * @param posx the new X coordinate
	 */
	public void setPosx(Double posx) {
		this.posx = posx;
	}

	/**
	 * Gets the Y coordinate.
	 *
	 * @return the Y coordinate
	 */
	public Double getPosy() {
		return this.posy;
	}

	/**
	 * Sets the Y coordinate.
	 *
	 * @param posy the new Y coordinate
	 */
	public void setPosy(Double posy) {
		this.posy = posy;
	}
	
	/**
	 * Checks if is out.
	 *
	 * @return true, if is out
	 */
	public boolean isOut() {
		return (this.out == OUT);
	}
	
	/**
	 * Sets if the plane is out.
	 */
	public void setOut() {
		this.out = OUT;
	}

	/**
	 * Gets the out.
	 *
	 * @return the out
	 */
	public int getOut() {
		return out;
	}

	/**
	 * Sets the out.
	 *
	 * @param out the new out
	 */
	public void setOut(int out) {
		this.out = out;
	}
	
}
