/*
 * 
 */
package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;

import engine.AirportEngine;
import engine.Enumerated.Sectors;
import threads.SynchronizationFactory;
import utils.HibernateUtils;

/**
 * Planes generated by hbm2java.
 * It implements runnable, and every plane is executed in a thread.
 */

@Entity
@Table(name = "Planes")
public class Planes implements Serializable, Runnable {

	/** The Constant serialVersionUID to avoid warnings. */
	private static final long serialVersionUID = 1L;

	/** The status arrive. */
	@Transient
	private final int STATUS_ARRIVE = 0;

	/** The status depart. */
	@Transient
	private final int STATUS_DEPART = 1;
	
	/** Airport engine, where the plane lands and takes of. */
	@Transient
	public AirportEngine ae;

	/** The plane id. */
	@Id
	@Column(name = "id")
	private int id;

	/** The airline id. */
	@Column(name = "Airline_id")
	private int airline_id;

	/** The plane model id. */
	@Column(name = "Plane_Model_id")
	private int planeModel_id;

	/** The plane status. It can be ARRIVE or DEPARTURE. */
	@Column(name = "Plane_Status_id")
	private int planeStatu_id;

	/** The terminal id. */
	@Transient
	private int terminal_id = -1;

	/**
	 * Instantiates a new planes.
	 */
	public Planes() {
	}

	/**
	 * Instantiates a new plane.
	 *
	 * @param id plane id
	 * @param airlines airline id
	 * @param planeModels plane model id
	 * @param planeStatus the plane status (ARRIVE or DEPARTURE)
	 */
	public Planes(int id, int airlines, int planeModels, int planeStatus) {
		this.id = id;
		this.airline_id = airlines;
		this.planeModel_id = planeModels;
		this.planeStatu_id = planeStatus;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the airline id.
	 *
	 * @return the airline id
	 */
	public int getAirline_id() {
		return airline_id;
	}

	/**
	 * Sets the airline id.
	 *
	 * @param airline_id the new airline id
	 */
	public void setAirline_id(int airline_id) {
		this.airline_id = airline_id;
	}

	/**
	 * Gets the plane model id.
	 *
	 * @return the plane model id
	 */
	public int getPlaneModel_id() {
		return planeModel_id;
	}

	/**
	 * Sets the plane model id.
	 *
	 * @param planeModel_id the new plane model id
	 */
	public void setPlaneModel_id(int planeModel_id) {
		this.planeModel_id = planeModel_id;
	}

	/**
	 * Gets the plane status.
	 *
	 * @return the plane status
	 */
	public int getPlaneStatu_id() {
		return planeStatu_id;
	}

	/**
	 * Sets the plane status.
	 *
	 * @param planeStatu_id the new plane status
	 */
	public void setPlaneStatu_id(int planeStatu_id) {
		this.planeStatu_id = planeStatu_id;
	}

	/**
	 * Gets the engine.
	 *
	 * @return the engine
	 */
	public AirportEngine getAe() {
		return ae;
	}

	/**
	 * Sets the engine.
	 *
	 * @param ae the new engine
	 */
	public void setAe(AirportEngine ae) {
		this.ae = ae;
	}

	/**
	 * Gets the terminal id.
	 *
	 * @return the terminal id
	 */
	public int getTerminal() {
		Session session = HibernateUtils.getSessionFactory().openSession();
		try {
			if (terminal_id == -1) {
				SynchronizationFactory.LOCKS.get(Sectors.AIRPORT).lock();
				Query query = session.createSQLQuery("select getTerminal(:plane)").setInteger("plane", this.id);
				terminal_id = Integer.parseInt(query.list().get(0).toString());
				SynchronizationFactory.LOCKS.get(Sectors.AIRPORT).unlock();
			}
		} catch (HibernateException e) {
			e.printStackTrace();
		} finally {
			session.close();
		}
		return terminal_id;
	}

	/**
	 * A sleep that simulates the plane moving.
	 *
	 * @throws InterruptedException the interrupted exception
	 */
	public void doMovement() throws InterruptedException {
		Thread.sleep(12000);
	}

	/**
	 * When an object implementing interface Runnable is used to create a thread, starting the thread causes the object's run method to be called in that separately executing thread. 
	 */
	@Override
	public void run() {
		ae = new AirportEngine();
		ae.land(this);
		try {
			this.doMovement();
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		ae.takeOff(this);
		Thread.currentThread().interrupt();
	}

}
